---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: lint
    image: golangci/golangci-lint:latest-alpine
    commands:
      - golangci-lint run --enable-all --disable gomnd
  - name: test
    image: golang:1-alpine
    commands:
      - CGO_ENABLED=0 go test -json -coverprofile=coverage.out ./... >tests.json
  - name: build
    image: golang:1-alpine
    commands:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-s -w" -o dist/github-latest_linux_amd64
      - CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -installsuffix cgo -ldflags="-s -w" -o dist/github-latest_linux_arm64
      - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-s -w" -o dist/github-latest_darwin_amd64
      - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-s -w" -o dist/github-latest_windows_amd64
    depends_on:
      - lint
      - test
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_access_token
      files: dist/*
      checksum:
        - sha256
      title: ${DRONE_TAG}
    depends_on:
      - build
    when:
      event: tag
