kind: pipeline
type: kubernetes
name: backend

steps:
  - name: lint
    image: golangci/golangci-lint:latest-alpine
    commands:
      - golangci-lint run --enable-all
  - name: test-build
    image: golang:1-alpine
    commands:
      - CGO_ENABLED=0 go test -json -coverprofile=coverage.out ./... >tests.json
      - CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags="-s -w" .
