name: check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.7
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up linters
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          curl -sSL -o /usr/local/bin/nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.30/nancy-v1.0.30-linux-amd64 && chmod 755 /usr/local/bin/nancy
      - name: Check out
        uses: actions/checkout@v2
      - name: Lint
        run: |
          make lint
          go list -json -m all | nancy sleuth
      - name: Build
        run: |
          go build .
