name: check

on:
  push:
  pull_request:

jobs:
  check:
    uses: ectobit/reusable-workflows/.github/workflows/go-check.yaml@main
    with:
      test-command: make test
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Build
        run: go build .
