name: release

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CMD_PATH: .
  BINARY_NAME: github-latest
  GO_VERSION: 1.17.2
  CGO_ENABLED: 0

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ['386', arm64, amd64]
        exclude:
          - goarch: '386'
            goos: windows
          - goarch: '386'
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: darwin
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.14
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 'https://golang.org/dl/go${{ env.GO_VERSION }}.linux-amd64.tar.gz'
          project_path: '${{ env.CMD_PATH }}'
          ldflags: -s -w
          build_flags: -a -installsuffix cgo
          binary_name: '${{ env.BINARY_NAME }}'
