name: update-deps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 0'

jobs:
  update-deps:
    uses: ectobit/reusable-workflows/.github/workflows/go-update-deps.yaml@main
    secrets:
      token: ${{ secrets.PAT }}
